 
  rmq-client:
    image: rmq-client
    ports:
      - "4201:4201"

  rmq-api:
    image: rmq-api
    ports:
      - "3001:3001"

  client:
    image: client
    ports:
      - "4200:4200"

  api:
    image: vacation-api
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
      - /home/willi/toTheCloud-/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
 my-db: # Don't declare it as external her
