version: '3.8'  # Use a supported version
services:
  api:
    image: vacation-api
    ports:
      - "3000:3000"
    networks:
      - default

  client:
    image: client
    ports:
      - "4200:4200"
    networks:
      - default

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - my-db:/var/lib/mysql
      - /home/willi/toTheCloud-/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /home/willi/.docker-conf/rabbitmq/data:/var/lib/rabbitmq
      - /home/willi/.docker-conf/rabbitmq/log:/var/log/rabbitmq
    networks:
      - default

  rmq-api:
    image: rmq-api
    ports:
      - "3001:3001"
    networks:
      - default

  rmq-client:
    image: rmq-client
    ports:
      - "4201:4201"
    networks:
      - default

networks:
  default:
    name: db_default

volumes:
  my-db:
    name: db_my-db
