version: '3.8'
services:
  rmq-client:
    image: rmq-client
    ports:
      - "4201:4201"

  rmq-api:
    image: rmq-api
    ports:
      - "3001:3001"

  client:
    image: client
    ports:
      - "4200:4200"

  api:
    image: vacation-api
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: rabbitOrder vacations
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  rabbitmq_data:
  rabbitmq_log:
  db_data:

